language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - pypy
install:
  - python setup.py develop
  - easy_install mr.bob[test]
script:
  - ./bin/test
matrix:
  allow_failures:
    - python: pypy
